[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
# These will be automatically provided by Railway
variables = { NODE_ENV = "production" }

[environments.development]
variables = { NODE_ENV = "development" }