[phases.setup]
cmds = [
  'apt-get update',
  'apt-get install -y wget gnupg ca-certificates',
  'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -',
  'sh -c "echo deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main >> /etc/apt/sources.list.d/google.list"',
  'apt-get update',
  'apt-get install -y google-chrome-stable fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libnss3 --no-install-recommends'
]

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm run start:prod'