[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install --production']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm run start:prod'