[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'chromium']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npx puppeteer browsers install chrome', 'npm run build']

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'false'

[start]
cmd = 'npm run start:prod'